import {useEffect,useRef,useState} from 'react'
import {ChevronDown,ChevronRight,Check, X} from 'lucide-react'
import type {Course,Lesson,State} from '../types'
// The lesson list is a drawer. It sits beside the lesson on wide screens and covers it on narrower ones (overlay).
export default function Curriculum({courses,lessons,state,current,onSelect,open,overlay,onClose}:{courses:Course[];lessons:Lesson[];state:State;current:Lesson;onSelect:(id:string)=>void;open:boolean;overlay:boolean;onClose:()=>void}){
 const [expanded,setExpanded]=useState<string[]>([current.course]);const completed=Object.keys(state.completed).length
 const aside=useRef<HTMLElement>(null)
 useEffect(()=>setExpanded(old=>old.includes(current.course)?old:[...old,current.course]),[current.course])
 // An overlay takes focus when it opens. Escape closes it, or the side panel when focus is inside it.
 useEffect(()=>{if(open&&overlay)(aside.current?.querySelector<HTMLElement>('.lesson-link.selected')||aside.current?.querySelector<HTMLElement>('.path-heading button'))?.focus()},[open,overlay])
 useEffect(()=>{if(!open)return;const onKey=(e:KeyboardEvent)=>{if(e.key!=='Escape'||(!overlay&&!aside.current?.contains(document.activeElement)))return;e.preventDefault();onClose()};document.addEventListener('keydown',onKey);return()=>document.removeEventListener('keydown',onKey)},[open,overlay,onClose])
 return <>{overlay&&<div className={'drawer-scrim '+(open?'visible':'')} aria-hidden="true" onClick={onClose}/>}<aside ref={aside} id="lesson-list" aria-labelledby="lesson-list-title" className={'curriculum '+(open?'open':'')}><div className="path-heading"><h2 id="lesson-list-title">Lessons</h2><button className="icon-button" aria-label="Hide lessons" onClick={onClose}><X size={19}/></button></div><p className="path-progress">{completed} of {lessons.length} lessons</p><div className="progress-track"><div style={{width:`${completed/lessons.length*100}%`}}/></div><div className="course-list">{courses.map((course,i)=>{const active=expanded.includes(course.id);return <section className="course" key={course.id}><button className="course-heading" onClick={()=>setExpanded(active?expanded.filter(c=>c!==course.id):[...expanded,course.id])} aria-expanded={active}><span className="course-number">{String(i+1).padStart(2,'0')}</span><span>{course.title}</span>{active?<ChevronDown size={16}/>:<ChevronRight size={16}/>}</button>{active&&<div className="lesson-list">{lessons.filter(l=>l.course===course.id).map((lesson,index)=><button className={'lesson-link '+(lesson.id===current.id?'selected':'')} key={lesson.id} onClick={()=>onSelect(lesson.id)} aria-current={lesson.id===current.id?'step':undefined}><span className={'lesson-number '+(state.completed[lesson.id]?'complete':'')}>{state.completed[lesson.id]?<Check size={15}/>:index+1}</span><span>{lesson.title}</span></button>)}</div>}</section>})}</div></aside></>
}
