import {useState} from 'react'
import {ArrowLeft,ArrowRight,ExternalLink,FolderGit2,Search} from 'lucide-react'
import type {Course,Lesson,State} from '../types'
import type {Portfolio,ProjectState} from '../portfolioTypes'
export default function Projects({data,courses,lessons,state,selected,initialFilter,onSelectProject,onLesson,onChange,saveStatus}:{data:Portfolio;courses:Course[];lessons:Lesson[];state:State;selected:string;initialFilter:string;onSelectProject:(id:string)=>void;onLesson:(id:string)=>void;onChange:(id:string,value:ProjectState)=>void;saveStatus:string}){
 const [query,setQuery]=useState('');const [filter,setFilter]=useState(initialFilter||'all')
 const project=data.projects.find(p=>p.id===selected)
 const start=(track:string)=>{const list=lessons.filter(l=>l.course===track);onLesson((list.find(l=>!state.completed[l.id])||list[0]).id)}
 const progress=project?data.projectState[project.id]||{notes:'',reviewed:[],updatedAt:0}:null
 const update=(patch:Partial<ProjectState>)=>{if(project&&progress)onChange(project.id,{...progress,...patch,updatedAt:Date.now()})}
 if(project&&progress)return <main className="hub"><div className="project-detail"><button className="back-link" onClick={()=>onSelectProject('')}><ArrowLeft size={16}/>All projects</button><span className="eyebrow">PROJECT PRACTICE · {project.visibility}</span><h1>{project.title}</h1><p className="project-summary">{project.summary}</p><div className="project-tags">{project.tracks.map(t=><button key={t} onClick={()=>start(t)}>{courses.find(c=>c.id===t)?.title}<ArrowRight size={13}/></button>)}</div><section className="project-practice"><div><h2>Trace the design. Explain the tradeoff.</h2><p>Open the project in your editor and work through these prompts. Checking a step records your own review; it does not run tests against the project.</p><div className="walkthrough-steps">{project.steps.map((step,i)=><label key={i}><input type="checkbox" checked={progress.reviewed.includes(i)} onChange={e=>update({reviewed:e.target.checked?[...progress.reviewed,i]:progress.reviewed.filter(n=>n!==i)})}/><span><small>STEP {i+1}</small>{step}</span></label>)}</div><div className="project-deliverable"><strong>Your deliverable</strong><p>{project.deliverable}</p></div><label className="project-notes-label" htmlFor="project-notes">Your observations & evidence</label><textarea id="project-notes" className="project-notes" value={progress.notes} maxLength={30000} placeholder="Trace a request or episode. Record file paths, an invariant, a failure case, and the evidence you would use to test it." onChange={e=>update({notes:e.target.value})}/><p className="project-save" role="status">{saveStatus} · {progress.reviewed.length}/{project.steps.length} steps reviewed</p></div><aside className="project-evidence"><FolderGit2 size={24}/><h3>Project context</h3><p>{project.evidence}</p>{project.localPath&&<><h4>Local checkout</h4><code>{project.localPath}</code></>}{project.repoUrl&&<a href={project.repoUrl} target="_blank" rel="noreferrer">Open GitHub repository<ExternalLink size={14}/></a>}<p className="evidence-note">Project details are stored on this computer. The workshop does not read or modify the checkout.</p></aside></section></div></main>
 return <main className="hub"><div className="hub-inner"><div className="section-heading project-heading"><div><span className="eyebrow">YOUR WORK, AS A LEARNING MAP</span><h1>Learn through your projects.</h1><p>Choose a familiar system. Find its engineering patterns. Practice the skills behind them.</p></div><FolderGit2 size={38}/></div>{data.error&&<p role="alert" className="portfolio-warning">{data.error}</p>}{data.projects.length===0?<section className="empty-projects"><h2>Add your first project</h2><p>Create <code>data/portfolio.json</code> using the example in <code>docs/project-learning.md</code>, then refresh. Connect a project to skill paths and give it a short walkthrough. The catalog stays local and is ignored by Git.</p></section>:<><div className="project-filters"><label className="project-search"><Search size={17}/><input aria-label="Search projects" placeholder="Search projects or engineering skills" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter projects by skill" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All engineering skills</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></div><div className="project-grid">{data.projects.filter(p=>(filter==='all'||p.tracks.includes(filter))&&`${p.title} ${p.summary} ${p.tracks.map(t=>courses.find(c=>c.id===t)?.title).join(' ')}`.toLowerCase().includes(query.toLowerCase())).map(p=><button className="project-card" key={p.id} onClick={()=>onSelectProject(p.id)}><div className="project-card-title"><FolderGit2 size={20}/><span>{p.visibility}</span></div><h2>{p.title}</h2><p>{p.summary}</p><div className="project-tags">{p.tracks.map(t=><span key={t}>{courses.find(c=>c.id===t)?.title}</span>)}</div><div className="project-card-bottom"><span>{data.projectState[p.id]?.reviewed.length||0}/{p.steps.length} reviewed</span><strong>Explore project <ArrowRight size={15}/></strong></div></button>)}</div>{!data.projects.some(p=>(filter==='all'||p.tracks.includes(filter))&&`${p.title} ${p.summary} ${p.tracks.map(t=>courses.find(c=>c.id===t)?.title).join(' ')}`.toLowerCase().includes(query.toLowerCase()))&&<p className="empty-projects">No projects match. Try another search or skill.</p>}<p className="hub-footnote">{data.coverage}</p></>}</div></main>
}
