import {useLayoutEffect,useRef,useState} from 'react'
import {ArrowLeft,ArrowRight,ExternalLink,FolderGit2,Search} from 'lucide-react'
import type {Course,Lesson,State} from '../types'
import type {Portfolio,ProjectState} from '../portfolioTypes'
export default function Projects({data,courses,lessons,state,selected,initialFilter,onSelectProject,onLesson,onChange,saveStatus}:{data:Portfolio;courses:Course[];lessons:Lesson[];state:State;selected:string;initialFilter:string;onSelectProject:(id:string)=>void;onLesson:(id:string)=>void;onChange:(id:string,value:ProjectState)=>void;saveStatus:string}){
 const container=useRef<HTMLElement>(null)
 useLayoutEffect(()=>{container.current?.scrollTo(0,0);if(window.matchMedia('(max-width:700px)').matches)window.scrollTo(0,0)},[selected])
 const [query,setQuery]=useState('');const [filter,setFilter]=useState(initialFilter||'all');const [level,setLevel]=useState('all')
 const project=data.projects.find(p=>p.id===selected)
 const start=(track:string)=>{const list=lessons.filter(l=>l.course===track);onLesson((list.find(l=>!state.completed[l.id])||list[0]).id)}
 const progress=project?data.projectState[project.id]||{notes:'',reviewed:[],updatedAt:0}:null
 const update=(patch:Partial<ProjectState>)=>{if(project&&progress)onChange(project.id,{...progress,...patch,updatedAt:Date.now()})}
 if(project&&progress)return <main ref={container} className="hub"><div className="project-detail"><button className="back-link" onClick={()=>onSelectProject('')}><ArrowLeft size={16}/>All projects</button><span className="eyebrow">{project.visibility==='public'?'Public project':'Project practice'} · {project.level}</span><h1>{project.title}</h1><p className="project-summary">{project.summary}</p><div className="project-tags">{project.tracks.map(t=><button key={t} onClick={()=>start(t)}>{courses.find(c=>c.id===t)?.title}<ArrowRight size={13}/></button>)}</div><div className="project-first-step"><div><h2>Why this project</h2><p>{project.why}</p></div><button className="primary-button" onClick={()=>onLesson(project.firstLesson)}>Preparation lesson: {lessons.find(l=>l.id===project.firstLesson)?.title}<ArrowRight size={15}/></button></div><section className="project-practice"><div><h2>Walkthrough</h2><p>Open the starting file, then work through the steps in order. Mark a step done when you can explain it. Notes and steps are saved on this computer.</p><div className="walkthrough-steps">{project.steps.map((step,i)=><label key={i}><input type="checkbox" checked={progress.reviewed.includes(i)} onChange={e=>update({reviewed:e.target.checked?[...progress.reviewed,i]:progress.reviewed.filter(n=>n!==i)})}/><span><small>Step {i+1}</small>{step}</span></label>)}</div><div className="project-deliverable"><strong>What to produce</strong><p>{project.deliverable}</p></div><label className="project-notes-label" htmlFor="project-notes">Notes</label><textarea id="project-notes" className="project-notes" value={progress.notes} maxLength={30000} placeholder="File paths, what must always hold, one way it can fail, how you would test it" onChange={e=>update({notes:e.target.value})}/><p className="project-save" role="status">{saveStatus} · {progress.reviewed.length}/{project.steps.length} steps done</p></div><aside className="project-evidence"><FolderGit2 size={24}/><h3>Start reading here</h3>{project.entryPoint.url&&<a className="source-entry" href={project.entryPoint.url} target="_blank" rel="noreferrer">{project.entryPoint.label}<ExternalLink size={14}/></a>}<h4>Before you begin</h4><p>{project.requirements}</p><h4>How this was checked</h4><p>{project.evidence}</p>{project.localPath&&<><h4>Local checkout</h4><code>{project.localPath}</code></>}{project.repoUrl&&<a href={project.repoUrl} target="_blank" rel="noreferrer">Open GitHub repository<ExternalLink size={14}/></a>}<p className="evidence-note">This is a link to an independent upstream project. The workshop does not install or run it for you.</p></aside></section></div></main>
 return <main ref={container} className="hub"><div className="hub-inner"><div className="section-heading project-heading"><div><h1>Projects</h1><p>Each project points to one file in a public GitHub repository and gives you steps to work through. Begin at the Start small level.</p></div><FolderGit2 size={38}/></div>{data.error&&<p role="alert" className="portfolio-warning">{data.error}</p>}{data.projects.length===0?<section className="empty-projects"><h2>No projects to show</h2><p>A data/portfolio.json file replaces the built-in catalog. Fix or remove it to see the built-in projects. See docs/project-learning.md.</p></section>:<><div className="project-filters"><label className="project-search"><Search size={17}/><input aria-label="Search projects" placeholder="Search projects or paths" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter projects by path" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All paths</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select><select aria-label="Filter projects by level" value={level} onChange={e=>setLevel(e.target.value)}><option value="all">All levels</option><option>Start small</option><option>Build next</option><option>Capstone</option></select></div><p className="project-ladder"><strong>Start small</strong><ArrowRight size={14}/><span>Build next</span><ArrowRight size={14}/><span>Capstone</span></p><div className="project-grid">{data.projects.filter(p=>(filter==='all'||p.tracks.includes(filter))&&(level==='all'||p.level===level)&&`${p.title} ${p.summary} ${p.tracks.map(t=>courses.find(c=>c.id===t)?.title).join(' ')}`.toLowerCase().includes(query.toLowerCase())).map(p=><button className="project-card" key={p.id} onClick={()=>onSelectProject(p.id)}><div className="project-card-title"><FolderGit2 size={20}/><span className={p.level==='Start small'?'starter-level':''}>{p.level}</span></div><h2>{p.title}</h2><p>{p.summary}</p><div className="project-tags">{p.tracks.map(t=><span key={t}>{courses.find(c=>c.id===t)?.title}</span>)}</div><div className="project-card-bottom"><span>{data.projectState[p.id]?.reviewed.length||0}/{p.steps.length} steps</span><strong>Open project <ArrowRight size={15}/></strong></div></button>)}</div>{!data.projects.some(p=>(filter==='all'||p.tracks.includes(filter))&&(level==='all'||p.level===level)&&`${p.title} ${p.summary} ${p.tracks.map(t=>courses.find(c=>c.id===t)?.title).join(' ')}`.toLowerCase().includes(query.toLowerCase()))&&<p className="empty-projects">No projects match. Try another search or path.</p>}<p className="hub-footnote">{data.coverage}</p></>}</div></main>
}
