import {useEffect,useRef,useState} from 'react'
import {CheckCircle2,Download,ExternalLink,Info,X} from 'lucide-react'
import type {Runtime} from '../types'
import type {GameSummary} from '../game/types'
export default function Settings({runtime,onBackup,onClose,game,onGameToggle}:{runtime:Runtime|null;onBackup:()=>Promise<{url:string;filename:string}>;onClose:()=>void;game:GameSummary|null;onGameToggle:(enabled:boolean)=>Promise<void>}){
 const dialog=useRef<HTMLDialogElement>(null)
 useEffect(()=>{dialog.current?.showModal()},[])
 const [backup,setBackup]=useState<{url:string;filename:string}|null>(null);const [backupStatus,setBackupStatus]=useState('')
 const [gameBusy,setGameBusy]=useState(false);const [gameError,setGameError]=useState('')
 async function toggleGame(enabled:boolean){setGameBusy(true);setGameError('');try{await onGameToggle(enabled)}catch(e){setGameError((e as Error).message)}finally{setGameBusy(false)}}
 async function exportProgress(){setBackupStatus('Saving backup…');try{setBackup(await onBackup());setBackupStatus('Backup saved on this computer')}catch(e){setBackupStatus((e as Error).message)}}
 return <dialog className="settings-dialog" ref={dialog} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><div className="dialog-header"><h2>Settings</h2><button className="icon-button" aria-label="Close settings" onClick={onClose}><X size={20}/></button></div><p className="dialog-intro">No account or API key needed.</p><div className="runtime-summary"><CheckCircle2 size={20}/><div><strong>Python {runtime?.python||'…'} · {runtime?.javascript?'Node.js ready':'Node.js unavailable'}</strong><span>Runs on this computer · one exercise at a time</span></div></div><h3>Installed frameworks</h3><dl className="package-list">{Object.entries(runtime?.packages||{}).map(([name,version])=><div key={name}><dt>{name}</dt><dd>{version||'Not installed'}</dd></div>)}</dl><div className="simulation-note"><Info size={18}/><span>CUDA runs in Numba’s CPU simulator. Learn kernel logic here; use an NVIDIA GPU later to validate compilation, timing, and memory performance.</span></div>{game&&<><h3>Hero game</h3><label className="game-toggle"><input type="checkbox" checked={game.enabled} disabled={gameBusy} onChange={e=>void toggleGame(e.target.checked)}/><span>Earn chests and battles as you finish lessons</span></label>{gameError&&<p className="game-toggle-error" role="alert">Could not change this setting: {gameError}</p>}<p className="game-toggle-note">{game.enabled?'Turn this off to hide the Hero tab and reward pop-ups.':'Hidden. Rewards still build up from your progress, so nothing is lost if you turn it back on.'}</p></>}<h3>Opening the app</h3><p>On macOS, open <strong>Engineering Workshop</strong> from Applications or your Desktop, or use <strong>Open ML Workshop.command</strong>. On Linux, run <strong>start.sh</strong>. On Windows, use <strong>Open Engineering Workshop.cmd</strong>. Closing the window or browser leaves the local server running.</p><p className="local-safety">The editor runs your Python and JavaScript with your user account’s permissions. Use code you trust. Framework packages and the app work offline; reference links need internet.</p><button className="secondary-button" onClick={exportProgress}><Download size={16}/>Export progress and notes</button><p className="backup-status" role="status">{backupStatus}{backup&&<> <a href={backup.url} download={backup.filename}>Download a copy</a></>}</p><a className="settings-reference" href="https://nvidia.github.io/numba-cuda/user/simulator.html" target="_blank" rel="noreferrer">CUDA simulator limitations<ExternalLink size={13}/></a></dialog>
}
