import {useEffect,useRef,useState} from 'react'
import {CheckCircle2,Download,ExternalLink,Info,X} from 'lucide-react'
import type {Runtime} from '../types'
export default function Settings({runtime,onBackup,onClose}:{runtime:Runtime|null;onBackup:()=>Promise<{url:string;filename:string}>;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null)
 useEffect(()=>{dialog.current?.showModal()},[])
 const [backup,setBackup]=useState<{url:string;filename:string}|null>(null);const [backupStatus,setBackupStatus]=useState('')
 async function exportProgress(){setBackupStatus('Saving backup…');try{setBackup(await onBackup());setBackupStatus('Backup saved on this Mac.')}catch(e){setBackupStatus((e as Error).message)}}
 return <dialog className="settings-dialog" ref={dialog} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><div className="dialog-header"><h2>Your local workshop</h2><button className="icon-button" aria-label="Close settings" onClick={onClose}><X size={20}/></button></div><p className="dialog-intro">Ready when you are. No account or API key required.</p><div className="runtime-summary"><CheckCircle2 size={20}/><div><strong>Python {runtime?.python||'…'}</strong><span>Runs on this Mac · one exercise at a time</span></div></div><h3>Installed frameworks</h3><dl className="package-list">{Object.entries(runtime?.packages||{}).map(([name,version])=><div key={name}><dt>{name}</dt><dd>{version||'Not installed'}</dd></div>)}</dl><div className="simulation-note"><Info size={18}/><span>CUDA runs in Numba’s CPU simulator. Learn kernel logic here; use an NVIDIA GPU later to validate compilation, timing, and memory performance.</span></div><h3>Pick up where you left off</h3><p>Open <strong>ML Workshop</strong> from your Desktop or Applications. It starts the server and opens your last lesson. Closing the browser keeps the lightweight server ready.</p><p className="local-safety">The editor runs your Python with your Mac user permissions. Use code you trust. Framework packages and the app work offline; reference links need internet.</p><button className="secondary-button" onClick={exportProgress}><Download size={16}/>Export progress & notes</button><p className="backup-status" role="status">{backupStatus}{backup&&<> <a href={backup.url} download={backup.filename}>Download a copy</a></>}</p><a className="settings-reference" href="https://nvidia.github.io/numba-cuda/user/simulator.html" target="_blank" rel="noreferrer">CUDA simulator limitations<ExternalLink size={13}/></a></dialog>
}
