import {useEffect,useRef,useState} from 'react'
import {CheckCircle2,X} from 'lucide-react'
import {CodeDiff,CodeLines} from './lazyCode'
import type {Lesson} from '../types'
export default function Solution({lesson,code,draft,onClose,onLoad}:{lesson:Lesson;code:string;draft:string;onClose:()=>void;onLoad:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null);const [compare,setCompare]=useState(false);const python=lesson.language!=='javascript'
 // Closing returns focus to the control that opened the dialog.
 useEffect(()=>{const opener=document.activeElement as HTMLElement|null;dialog.current?.showModal();return()=>{if(opener?.isConnected)opener.focus()}},[])
 return <dialog ref={dialog} className="solution-dialog" aria-label="Worked solution" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><div className="dialog-header"><h2>Solution</h2><button className="icon-button" aria-label="Close solution" onClick={onClose}><X size={20}/></button></div><h3>{lesson.title}</h3><p className="answer-explanation">{lesson.explanation}</p><div className="code-toggle" role="group" aria-label="Code to show"><button aria-pressed={!compare} onClick={()=>setCompare(false)}>Solution</button><button aria-pressed={compare} onClick={()=>setCompare(true)}>Compare with my code</button></div>{compare?<CodeDiff mine={draft} solution={code} python={python}/>:<CodeLines code={code} python={python} label="Solution code"/>}<div className="answer-checks"><h3>Checks this solution passes</h3><ul>{lesson.checkLabels.map(label=><li key={label}>{label}</li>)}</ul></div><p className="answer-load-note">Load into editor replaces your code. Showing the solution before you pass this lesson gives you a smaller chest for it in the Hero game. Showing it changes nothing else.</p><div className="button-row"><button className="secondary-button" onClick={onClose}>Back to lesson</button><button className="primary-button" onClick={onLoad}><CheckCircle2 size={16}/>Load into editor</button></div></dialog>
}
