import {lazy,Suspense,useCallback,useEffect,useRef,useState} from 'react'
import {CodeXml,Settings as SettingsIcon,Menu,LoaderCircle,X} from 'lucide-react'
import {api,bootstrap} from './api'
import type {Course,Lesson,State,Runtime,RunResult} from './types'
import Curriculum from './components/Curriculum'
import LessonReader from './components/LessonReader'
import Workspace from './components/Workspace'
import Overview from './components/Overview'
import Settings from './components/Settings'
import Solution from './components/Solution'
import type {BookLocation,LibraryData} from './libraryTypes'
const BookLibrary=lazy(()=>import('./components/BookLibrary'))
function bookRoute():BookLocation|null {const match=location.hash.match(/^#books\/([a-z0-9-]+)\/(\d+)(?:\/(.*))?$/);if(!match)return null;let anchor='';try{anchor=decodeURIComponent(match[3]||'')}catch{}return {bookId:match[1],location:Number(match[2]),anchor}}

const localKey='ml-workshop-drafts-v1'
type Draft={code:string;notes:string;updatedAt:number}
function readCache():Record<string,Draft>{try{return JSON.parse(localStorage.getItem(localKey)||'{}')}catch{return {}}}
export default function App(){
 const [library,setLibrary]=useState<LibraryData>({books:[],guides:[],readingState:{}});const [bookSelection,setBookSelection]=useState<BookLocation|null>(bookRoute)
 useEffect(()=>{const sync=()=>{if(location.hash.startsWith('#books')){setBookSelection(bookRoute());setPage('books')}else{setPage('learn')}};window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[])
 function showPage(next:'learn'|'practice'|'progress'|'books'){setPage(next);if(next==='books'){setBookSelection(null);location.hash='books'}else{history.replaceState(null,'',location.pathname+location.search)}}
 const [courses,setCourses]=useState<Course[]>([]);const [lessons,setLessons]=useState<Lesson[]>([]);const [state,setState]=useState<State|null>(null);const [runtime,setRuntime]=useState<Runtime|null>(null);const [id,setId]=useState('foundations-1');const [page,setPage]=useState<'learn'|'practice'|'progress'|'books'>(location.hash.startsWith('#books')?'books':'learn');const [drawer,setDrawer]=useState(false);const [settings,setSettings]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [results,setResults]=useState<Record<string,RunResult>>({});const [saveStatus,setSaveStatus]=useState('Saved on this Mac');const [solution,setSolution]=useState<string|null>(null);const [cache,setCache]=useState(readCache);const cacheRef=useRef(cache);const timers=useRef<Record<string,ReturnType<typeof setTimeout>>>({});const [loaded,setLoaded]=useState(false)
 useEffect(()=>{let active=true;(async()=>{try{await bootstrap();const [curriculum,s,r,books]=await Promise.all([api<{courses:Course[];lessons:Lesson[]}>('/curriculum'),api<State>('/state'),api<Runtime>('/runtime'),api<LibraryData>('/library')]);if(!active)return;const recovered=Object.fromEntries(Object.entries(cacheRef.current).filter(([key,draft])=>draft.updatedAt >= (s.draftUpdated?.[key]??0)));cacheRef.current=recovered;setCache(recovered);try{localStorage.setItem(localKey,JSON.stringify(recovered))}catch{};setCourses(curriculum.courses);setLessons(curriculum.lessons);setState(s);setId(s.currentLesson);setRuntime(r);setLibrary(books);setLoaded(true)}catch(e){if(active)setError((e as Error).message)}})();return()=>{active=false}},[])
 const save=useCallback(async(lessonId:string,draft:Draft)=>{try{await api('/draft',{lessonId,...draft});setSaveStatus('Saved on this Mac')}catch{setSaveStatus('Saved in browser · reconnect to sync')}},[])
 // Replay local recovery drafts when the server reconnects.
 useEffect(()=>{if(loaded)Object.entries(cacheRef.current).forEach(([lessonId,draft])=>{void save(lessonId,draft)})},[loaded,save])
 function updateDraft(lessonId:string,code:string,notes:string){const draft={code,notes,updatedAt:Date.now()};const next={...cacheRef.current,[lessonId]:draft};cacheRef.current=next;setCache(next);try{localStorage.setItem(localKey,JSON.stringify(next));setSaveStatus('Saving…')}catch{setSaveStatus('Browser storage full · saving to server')};clearTimeout(timers.current[lessonId]);timers.current[lessonId]=setTimeout(()=>void save(lessonId,draft),350)}
 function selectLesson(next:string){if(busy)return;history.replaceState(null,'',location.pathname+location.search);setId(next);setPage('learn');setSolution(null);setError('');void api('/current',{lessonId:next}).catch(()=>setSaveStatus('Could not save last lesson · retry after reconnect'))}
 if(!state||!lessons.length)return <main className="loading-screen"><CodeXml size={44}/><h1>Opening your workshop.</h1>{error?<><p>{error}</p><button className="primary-button" onClick={()=>location.reload()}>Reconnect</button></>:<LoaderCircle size={23} className="spin"/>}</main>
 const lesson=lessons.find(l=>l.id===id)||lessons[0];const course=courses.find(c=>c.id===lesson.course)!;const inCourse=lessons.filter(l=>l.course===lesson.course);const position=lessons.indexOf(lesson);const code=cache[id]?.code??state.drafts[id]??lesson.starter;const notes=cache[id]?.notes??state.notes[id]??'';const completed=!!state.completed[id]
 async function run(mode:'run'|'check'){if(busy)return;setBusy(true);setError('');try{await save(id,{code,notes,updatedAt:Date.now()});const result=await api<RunResult>('/run',{lessonId:id,code,mode});setResults(old=>({...old,[id]:result}));if(result.state)setState(result.state)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function showSolution(){try{const r=await api<{solution:string}>('/solution/'+id);setSolution(r.solution)}catch(e){setError((e as Error).message)}}
 async function backup(){await Promise.all([...Object.entries(cacheRef.current).map(([lessonId,draft])=>api('/draft',{lessonId,...draft})),...Object.entries(library.readingState).map(([bookId,reading])=>api('/library/state',{bookId,...reading}))]);return api<{url:string;filename:string}>('/backup',{})}
 return <div className="app"><header className="app-header"><div className="brand-area"><button className="icon-button mobile-only" style={page==='books'?{display:'none'}:undefined} aria-label="Open learning path" onClick={()=>setDrawer(true)}><Menu size={21}/></button><button className="brand" onClick={()=>showPage('learn')}><CodeXml size={29}/><span>ML Workshop</span></button></div><nav aria-label="Main navigation">{(['learn','practice','progress','books'] as const).map(p=><button key={p} className={page===p?'active':''} onClick={()=>showPage(p)}>{p[0].toUpperCase()+p.slice(1)}</button>)}</nav><div className="header-right"><button className="runtime-status" onClick={()=>setSettings(true)}><span/>Local Python</button><button className="icon-button" aria-label="Open settings" onClick={()=>setSettings(true)}><SettingsIcon size={20}/></button></div></header>{error&&<div role="alert" className="error-toast"><span>{error}</span><button aria-label="Dismiss error" onClick={()=>setError('')}><X size={17}/></button></div>}<div className="app-body">{page!=='books'&&<Curriculum courses={courses} lessons={lessons} state={state} current={lesson} onSelect={selectLesson} open={drawer} onClose={()=>setDrawer(false)}/>} {page==='books'?<Suspense fallback={<p className="book-hint">Opening your library…</p>}><BookLibrary data={library} selection={bookSelection} onLesson={selectLesson} onState={(bookId,value)=>setLibrary(old=>({...old,readingState:{...old.readingState,[bookId]:value}}))}/></Suspense>:page==='learn'?<main className="learning-layout"><LessonReader key={'reader-'+id} readings={library.guides.filter(g=>g.lessons.includes(lesson.id))} lesson={lesson} course={course} index={inCourse.indexOf(lesson)} count={inCourse.length} notes={notes} onNotes={s=>updateDraft(id,code,s)} onSolution={showSolution} onPath={()=>setPage('practice')}/><Workspace key={'workspace-'+id} lesson={lesson} code={code} onCode={s=>updateDraft(id,s,notes)} onRun={run} busy={busy} result={results[id]||null} done={completed} onPrevious={()=>selectLesson(lessons[position-1].id)} onNext={()=>selectLesson(lessons[position+1].id)} hasPrevious={position>0} hasNext={position<lessons.length-1} saveStatus={saveStatus}/></main>:<Overview page={page} courses={courses} lessons={lessons} state={state} onSelect={selectLesson}/>}</div>{settings&&<Settings runtime={runtime} onBackup={backup} onClose={()=>setSettings(false)}/>} {solution&&<Solution code={solution} onClose={()=>setSolution(null)} onLoad={()=>{updateDraft(id,solution,notes);setSolution(null)}}/>}</div>
}
